baseURL = "https://startupeveryone.com/"
languageCode = "en-us"
title = "Startup Everyone"
publishdir = "./docs"

[build]
writeStats = true

[security.exec]
# https://github.com/gohugoio/hugo/issues/9811#issuecomment-1105842107
# osEnv = ['.*']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$', '(?i)^ASDF', '(?i)^HOME$']
